---
title: "programming.examples"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Lecture notes for today

[Programming](programming.pdf)

## Examples of the use of factors

Example of using a function
```{r function use}

source("autopower.R")
autopower
v=seq(from=0, to=100, by=10)
plot(v, autopower(V=0.447*v, m=31752, A=25))
lines(v, autopower(V=0.447*v, m=61752, A=25))



```


```{r fishes}

possible.fish = as.factor(c("salmon","steelhead","shark","tuna","cod"))
# simulate a random recording of catch by fisherman

catch1 = sample(possible.fish, size=10, replace=T)
catch1
summary(catch1)
plot(catch1, col="blue")


# use summary to explore and return information
mean(summary(catch1))
max(summary(catch1))

tmp = which.max(summary(catch1))
tmp
names(tmp)

plottitle=sprintf("We like %s", names(which.max(summary(catch1))))
plot(catch1, col="blue", main=plottitle)


plottitle=sprintf("We like %s", names(tmp))
plot(catch1, col="blue", main=plottitle)

plottitle  = sprintf("We like %s", names(summary(catch1)))
plot(catch1, col="blue", main=plottitle)




```

##  Functions with factors
You can return factors from functions
But lists might be better..

```{r diversitylist, echo=FALSE}

compute_simpson_index = function(species) {

species = as.factor(species)
tmp = (summary(species)/sum(summary(species))) ** 2
diversity = sum(tmp)
return(diversity)
}

possible.fish = as.factor(c("salmon","steelhead","shark","tuna","cod"))
# simulate a random recording of catch by fisherman

catch1 = sample(possible.fish, size=10, replace=TRUE)
catch2 = as.factor(c(rep("salmon", times=6), rep("cod",times=4)))

compute_simpson_index(catch1)
compute_simpson_index(catch2)


# repeat with a list
source("computediversity.R")
computediversity(catch1)
computediversity(catch2)
```
We can also use for loops to run a function multiple times

```{r npvfor, echo=FALSE}

# get function
source("compute_NPV.R")
compute_NPV(20, discount=0.01, time=20)


#generate some input
damages = c(25,33,91,24)
# sensitivity to discount rate
discount_rates = seq(from=0.01, to=0.04, by=0.005)
yr=10

# compute some npv's for different discount rates
# first generate a dataframe to store results
npvs = as.data.frame(matrix(nrow=length(damages), ncol=length(discount_rates)))

# now use a for loop to populate
 for (i in 1:length(damages)) {
         for (j in 1:length(discount_rates)) {
       npvs[i,j]= compute_NPV(value=damages[i],       discount=discount_rates[j],time=yr )

         }
 }
 npvs
 
 
 #some data wrangling
colnames(npvs)=discount_rates
rownames(npvs)=damages
 npvs
 

 npvs = gather(npvs, 1:7, key=dis, value=npv)
 head(npvs)
 ggplot(npvs, aes(x=npv, col=as.factor(dis)))+geom_density(size=2)+scale_color_brewer(type="seq", name="Discount")
 
 # how about summing all the damages
 npv.total =npvs %>% group_by(dis) %>% summarize(t=sum(npv))
 ggplot(npv.total, aes(dis,t, fill=dis))+geom_col() + labs(x="Discount Rate", y="Total ($)")

 source("compute_yield_NPV.R")
 # use functions inside a function
 T = c(15,18,20,25,26)
 P = c(200,200,200,200,200)
 compute_yield_NPV(T, P, ts=0.5, tp=0.5, intercept=200, irr="N", discount=0.02, price=2)
 
```
 
```{r str, echo=FALSE}

source("compute_season_meanflow.R")
source("compute_season_meanflow2.R")
str = read.table("str.txt", header=T)
compute_seasonal_meanflow(str)

compute_seasonal_flow(str)
compute_seasonal_flow(str, kind="max")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
